version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    commit-message:
      prefix: "ci:"
    schedule:
      interval: monthly
    reviewers:
      - "vitalvas"
    assignees:
      - "vitalvas"
